### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ahead' of null

### ISSUE THREAD

**Issue by heatwaveo8** [andischerer/atom-svn#28]
Atom Version: 1.9.1
SVN Version: 0.0.12

I am getting this error after an upgrade to Atom 1.9.1:

```
Uncaught TypeError: Cannot read property 'ahead' of null
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213
Hide Stack Trace
TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
The error was thrown from the status-bar package. This issue has already been reported.
```

After disabling all packages, and rebooting Atom a few times while doing some testing, I believe the svn package is causing the issue.

I'm currently unable to properly switch between tabs or search for content in files while the extension is enabled because of this. Please take a look.

**Comment by Xcodo** [comment]
See this issue https://github.com/atom/status-bar/issues/161.

Pretty annoying as you were forced to update the package to use async in 1.7.0.

Can we basically roll back to 0.0.9 somehow?

**Comment by 0rvar** [comment]
The patches to atom-svn only added an async api, this error seems to be
caused by a further api change. I will take a look at this next week, but
pull requests are welcome.

**Comment by Xcodo** [comment]
Yes, you're right. Looks like #27 has a possible solution

**Comment by derwaldgeist** [comment]
Any chance to get #27 merged soon? This error is like a déjà-vu for me, since there was a similar problem just recently that had been caused by an API change...

**Comment by heatwaveo8** [comment]
True, I saw that issue as well... status-bar was the extension reporting the error, but svn was the source. I wish Atom would be more specific in their errors to also specify any third-party extension(s) causing them, so bugs don't have to be reported in the wrong place.

**Comment by Xcodo** [comment]
Thanks @awestroke, 0.0.13 seems to work well for me so far.

**Comment by heatwaveo8** [comment]
After updating to 0.0.13 and re-booting Atom all works great! Thanks so much. Closing the issue.

**Comment by derwaldgeist** [comment]
Thanks a lot for fixing this so quickly!
